### ISSUE TITLE
Website is not working

### ISSUE THREAD

**Issue by andypiper** [dcooperdalrymple/pico_synth_sandbox-hardware#1]
Raising an issue here in an effort to let you know that https://pico-synth-sandbox.dcdalrymple.com/ is currently reporting a WordPress error (and the project has just been shared on the Make magazine news feed, so I’m likely not the only one hitting the issue…)

looking forward to learning more about the board when the site is back!

**Comment by relic-se** [comment]
Hi Andy, thanks for the heads up. I was actually already in the process of fixing my server and the site is live once again. Definitely picked a bad time to perform a shoddy PHP upgrade.
